version: '3.2'

volumes:
  cloud-postgres:
    driver: local
  cloud-files:
    driver: local

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    image: postgres:9.6
    container_name: cloud-postgres
    volumes:
      - type: volume
        source: cloud-postgres
        target: /var/lib/postgresql/dataConfig
    networks:
      - postgres-network
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5435:5432"
  cloud-server:
    build: .
    container_name: cloud-server
    volumes:
      - type: volume
        source: cloud-files
        target: /app
    networks:
      - postgres-network
    ports:
      - "8189:8189"