package command.domain;

public enum CommandCode {
    AUTH, LS, SUCCESS, FAIL, DOWNLOAD, UPLOAD, FILES_REQUEST, FILES_OFFER,
    UPLOAD_READY, DOWNLOAD_READY, DOWNLOAD_POSSIBLE, UPLOAD_POSSIBLE, REGISTER_REQUEST,
    OFFER_REFUSED, REFRESH_VIEW, REMOVE_FILE
}
